name: Publish to PyPi

on:
  workflow_dispatch:
    branches: [main]
permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - run: uv sync
      - run: uv build
      - run: uv publish
